### ISSUE TITLE
Testcase result png images in 0.3.0.2

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/IGUANA#24]
Hey,

IGUANA 0.2.1 created beside the result CSV tables for each file a png diagramm. In version 0.3.0.2 they seems not exists anymore. Is there a way to get them back again?

Thanks,
s

**Comment by TortugaAttack** [comment]
Currently not. The Problem was the png diagramm needs an unbearable amount of memory, which leads to many Java Heap Size exceeds Excpetion which will immediately abort IGUANA.
But it'll be an option in the Friday update where you can define if the resultprocessing should create the diagramms. So if you think it's worth it and you have enough memory you can produce them. 

Also in the next Version (probably round about mid January) there will be more beatiful diagramms and hopefully the possibility of not only bar charts. ;)

**Comment by simeonackermann** [comment]
Ok, thanks a lot! Since I had no problems with the memory in 0.2 I would try to activate it again.
For me the simple chart bars are good enough, so I'm looking with interest to the friday update...

**Comment by TortugaAttack** [comment]
Friday Update is a little early, as I'm probably not in office tomorrow, so the Update is finished:

just put 
<save-results-as-diagram value="true"/> in your suites  
<suite>
...
<save-results-as-diagram value="true"/>
...
</suite>

You can optionally get another format (png (default), jpg, gif, bmp, svg, pdf, eps):
<save-results-as-diagram value="true" format="svg"/> 

hope everything else works fine for you :)

**Comment by simeonackermann** [comment]
Works like a charm. Thanks a lot!
