### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/IGUANA#29]
Hey,

what kind of authentication uses IGUANA for the benchmark testcases?
I'm trying to benchmark an elds, which is OAuth 2 protected, could this work?

Thanks a lot - this might be my last question for now ;)

Greetings

**Comment by TortugaAttack** [comment]
Depends on what you want to test ;) 
The SPARQL Users useses the jena jdbc remote lib to get the results. I don't know which authentication they use. 
The updates are "self implemented" with the following lines: 
```
CredentialsProvider provider = new BasicCredentialsProvider();				provider.setCredentials(new AuthScope(AuthScope.ANY_HOST,
			AuthScope.ANY_PORT), new UsernamePasswordCredentials(user, pwd));
httpContext.setAttribute(ClientContext.CREDS_PROVIDER, provider);
```

Could work. As i don't have the knowledge about authentication, i really can't say. sorry. 
May the code snippet helps. Otherwise try a small benchmark and look into the results if every query failed, the chances are high that the authentication doesn't work.

Hope i could at least help a little bit. 
If it worked (or not) please write it down. If so nice, else i'll work on that ;) 

Greetings

**Comment by simeonackermann** [comment]
OK, many thanks for the info, it helped to find the "solution".

It seems the jena lib uses http auth like basic and digest [1], which seems not compatible with oauth because all benchmarks failed.

I think you can close the issue, because it belonged to the jena lib...


[1] https://jena.apache.org/documentation/jdbc/drivers.html#authentication

**Comment by TortugaAttack** [comment]
Okay. Thanks for the info. 
I'll build a Connection which can work with Oauth too ;) 
Ticket can be found here #30
